### ISSUE TITLE
API: Bulk Insert with automatic parse

### ISSUE THREAD

**Issue by a0xz** [w1ld3r/Rotulus#11]
You can develop bulk insert in the api with automatic parse. 

Example:
file.txt
a@a.com:aa
b@b.com:bb 

Send for the api and the server parse automatic with the model:
email, user, domain, password

**Comment by w1ld3r** [comment]
Hello @a0xz, I've already done tests with templates combinaisons. It's cool but give you a lot of wrong values.
I've been using a array of templates like this one:
`['{password}:{local_part}@{domain}','{local_part}@{domain}:{password}']`
and for each template in the array I parse the file.
This give you a lot a wrong value because it doesn't take care of results done by previous templates.
Maybe by testing each line against each template and taking the best match will give less errors...
